import type { Workout } from "@trainiq/types";

export const mockWorkoutLibrary: Workout[] = [
  // Cycling
  {
    id: "cyc-z2-60",
    name: "Z2 Ride (60 min)",
    sport: "cycling",
    durationMinutes: 60,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 3,
    description: "Steady aerobic ride in Zone 2, conversational pace throughout.",
  },
  {
    id: "cyc-z2-90",
    name: "Z2 Ride (90 min)",
    sport: "cycling",
    durationMinutes: 90,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 4,
    description: "Steady aerobic ride in Zone 2, conversational pace throughout.",
  },
  {
    id: "cyc-z2-150",
    name: "Z2 Ride (2h30)",
    sport: "cycling",
    durationMinutes: 150,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 6,
    description: "Extended aerobic ride in Zone 2, building durability for climbing.",
  },
  {
    id: "cyc-z2-180",
    name: "Z2 Ride (3h)",
    sport: "cycling",
    durationMinutes: 180,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 7,
    description: "Long aerobic ride in Zone 2, the week's endurance cornerstone.",
  },
  {
    id: "cyc-sweet-spot",
    name: "Sweet Spot",
    sport: "cycling",
    durationMinutes: 75,
    focus: "sweet-spot",
    intensity: "hard",
    fatigueCost: 6,
    description: "3 x 15 min at 88-94% FTP with 5 min recovery between efforts.",
  },
  {
    id: "cyc-over-under",
    name: "Over-Under",
    sport: "cycling",
    durationMinutes: 70,
    focus: "over-under",
    intensity: "hard",
    fatigueCost: 7,
    description: "4 x 12 min alternating 2 min over / 2 min under FTP.",
  },
  {
    id: "cyc-map",
    name: "MAP",
    sport: "cycling",
    durationMinutes: 60,
    focus: "vo2max",
    intensity: "very-hard",
    fatigueCost: 8,
    description: "6 x 3 min at maximal aerobic power with 3 min recovery.",
  },
  {
    id: "cyc-threshold",
    name: "Threshold",
    sport: "cycling",
    durationMinutes: 60,
    focus: "threshold",
    intensity: "hard",
    fatigueCost: 7,
    description: "2 x 20 min at FTP with 10 min recovery between efforts.",
  },
  {
    id: "cyc-openers",
    name: "Openers",
    sport: "cycling",
    durationMinutes: 30,
    focus: "openers",
    intensity: "easy",
    fatigueCost: 2,
    description: "Short spin with a few brief high-cadence efforts to stay sharp.",
  },
  // Running
  {
    id: "run-endurance-45",
    name: "Run - Endurance (45 min)",
    sport: "running",
    durationMinutes: 45,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 3,
    description: "Easy aerobic run at conversational pace.",
  },
  {
    id: "run-endurance-60",
    name: "Run - Endurance (60 min)",
    sport: "running",
    durationMinutes: 60,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 4,
    description: "Easy aerobic run at conversational pace.",
  },
  {
    id: "run-endurance-90",
    name: "Run - Endurance (90 min)",
    sport: "running",
    durationMinutes: 90,
    focus: "endurance",
    intensity: "easy",
    fatigueCost: 5,
    description: "Longer easy aerobic run, building durability.",
  },
  {
    id: "run-seuil",
    name: "Run - Seuil",
    sport: "running",
    durationMinutes: 50,
    focus: "threshold",
    intensity: "hard",
    fatigueCost: 6,
    description: "3 x 8 min at threshold pace with 2 min jog recovery.",
  },
  {
    id: "run-tempo",
    name: "Tempo",
    sport: "running",
    durationMinutes: 45,
    focus: "tempo",
    intensity: "moderate",
    fatigueCost: 5,
    description: "20 min continuous tempo effort, comfortably hard.",
  },
  {
    id: "run-vo2",
    name: "VO2",
    sport: "running",
    durationMinutes: 40,
    focus: "vo2max",
    intensity: "very-hard",
    fatigueCost: 7,
    description: "6 x 3 min at VO2max pace with 3 min jog recovery.",
  },
  // Strength (complementary modality, not an endurance sport slot)
  {
    id: "str-core-mobility",
    name: "Core & Mobility",
    sport: "strength",
    durationMinutes: 30,
    focus: "strength",
    intensity: "easy",
    fatigueCost: 2,
    description: "Bodyweight core circuit and mobility work — low fatigue cost.",
  },
  {
    id: "str-full-body",
    name: "Full-Body Strength",
    sport: "strength",
    durationMinutes: 45,
    focus: "strength",
    intensity: "moderate",
    fatigueCost: 5,
    description: "Compound lower- and upper-body lifts, general strength maintenance.",
  },
];
